version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - 3390:3306

    environment:
      MYSQL_DATABASE: ticketexchange
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


  app:
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3390
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ticketexchange
    depends_on:
      - db
    ports:
      - "8090:8080"