variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonar

build:
  stage: build
  script:
    - cd 'Semester 3 project'
    - ./gradlew assemble

test:
  stage: test
  allow_failure: true
  script:
    - cd 'Semester 3 project'
    - ./gradlew test

sonar:
  stage: sonar
  script:
    - cd 'Semester 3 project'
    - ./gradlew sonarqube
